"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
from setuptools import setup


APP = ['Traktor Librarian.py']
DATA_FILES = [('', ['static']), ('', ['templates'])]
OPTIONS = {'argv_emulation': False,
           'strip': True,
           'iconfile': 'icon.icns',
           'includes': ['WebKit', 'Foundation']}

if sys.platform == "darwin":
    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
    )
elif sys.plaform == "win32":
    setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2exe': OPTIONS},
        setup_requires=['py2exe'],
        )